---
author: "Jaakko Kähärä"
title: "IODS course project"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
---

------------------------------------------------------------------------

# Chapter 1

```{r child = "chapter1.Rmd"}
# link to chapter 1
```

------------------------------------------------------------------------

# Chapter 2

```{r child = "chapter2.Rmd"}
# link to chapter 2
```

------------------------------------------------------------------------

# Chapter 3

```{r child = "chapter3.Rmd"}
# link to chapter 3
```

------------------------------------------------------------------------

# Chapter 4

```{r child = "chapter4.Rmd"}
# link to chapter 4
```

------------------------------------------------------------------------

# Chapter 5

```{r child = "chapter5.html", echo=FALSE}
# link to chapter 5
```

------------------------------------------------------------------------

# Chapter 6

```{r child = "chapter6.html", echo=FALSE}
# link to chapter 6
```


